### ISSUE TITLE
插桩后，导致按钮点击失效的问题

### ISSUE THREAD

**Issue by miqt** [growingio/growingio-sdk-android-autotracker#159]
### 描述你的问题以及如何重现

插桩后导致原来有效的点击事件失效

示例：

public class B implements View.OnClickListener{
    @Override
    public void onClick(View v) {
        //点击逻辑
    }
}

public class A extends B implements View.OnClickListener {

}

由于A没自己实现onClick方法，导致，插桩自动创建onClick方法，但创建后的方法没有调用super()，因此，实际在B中的点击逻辑会失效

接口类型是否不需要进行方法生成？

**Comment by cpacm** [comment]
接口这部分若考虑继承关系，则会出现很多问题，比如下面的代码：
```java
public abstract class A implements View.OnClickListener {
}

public class B extends A {
      @Override
      public void onClick(View v) {
      }
}
```
明显 B 这个类下的 onClick 方法无法通过插件注入Hook代码。

_**现在插件只能保证继承接口的当前类下的方法能够通过插件注入 Hook 代码。**_

若考虑继承则可能需要再重新设计，比如直接在 'MethodVisitor' 中判断是否 'onClick(Landroid/view/View;)V' 来保证所有方法都能注入。

**Comment by miqt** [comment]
了解了，谢谢
