### ISSUE TITLE
你这里SDK文档和官网SDK文档有什么区别？作为开发者，需要集成哪一个

### ISSUE THREAD

**Issue by bingowang1991** [growingio/growingio-sdk-android-autotracker#169]
### 问题描述

你这里SDK文档和官网SDK文档有什么区别？作为开发者，需要集成哪一个

### 相关的URL链接

https://docs.growingio.com/v3/developer-manual/sdkintegrated/android-sdk/androidsdk-log

### 提供一份截图以供我们快速定位

![image](https://user-images.githubusercontent.com/12081463/183417001-7a035168-219f-401d-9449-e03f395ed8f5.png)

### 这是浏览器特有的问题吗?如果是，请描述下设备、浏览器版本相关信息。

```true
没有
```

**Comment by cpacm** [comment]
Saas 和 Cdp（需要同时集成我们的客户数据平台） 的区别，请根据公司购买的产品集成对应的SDK。
